license_id: "cc-by-igo"
subnational: 1  # has to be 0 or 1
notes: Contains data from World Food Programme [data portal](http://dataviz.vam.wfp.org/) focusing on prices of basic food commodities.
caveats: ""
methodology: "Registry"
dataset_source: "World Food Programme - VAM"
package_creator: "orest-d"
private: False  # has to be True or False
